name: browserslist-update-action
description: Runs `npx browserslist@latest --update-db` on a repository and proposes a pull request to merge updates.
author: Camptocamp Association
branding:
  icon: bar-chart-2
  color: green
inputs:
  github_token:
    description: Github secret
    required: true
  branch:
    description: Branch used for pull request
    required: false
    default: browserslist-update
runs:
  using: 'node12'
  main: 'dist/index.js'
